name: Trigger Test Manual with Configuration
on:
  workflow_dispatch:
    inputs:
      Browser:
        description: 'Select the Browser'
        options:
          - firefox
          - chrome
          - electron
        type: choice
        default: chrome
        required : true
      Headed:
        description: "Do you want to run tests in Headed mode??"
        type: boolean
        required: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Cypress tests on ${{inputs.Browser}} Browser in ${{inputs.Headed}} Headed mode
      uses: cypress-io/github-action@v6
      with: 
        cond: ${{inputs.Headed}}
        if_true: cypress run --browser ${{inputs.Browser}} --headed || npm run posttest
        if_false: cypress run --browser ${{inputs.Browser}} || npm run posttest

            
        