name: Trigger Test Manual with Configuration
on:
  workflow_dispatch:
    inputs:
      Browser:
        description: 'Select the Browser'
        options:
          - firefox
          - chrome
          - electron
        type: choice
        default: chrome
        required : true
      Headed:
        description: "Do you want to run tests in Headed mode??"
        type: boolean
        required: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Cypress tests on ${{inputs.Browser}} Browser in ${{inputs.Headed}}
      uses: cypress-io/github-action@v6
      with: 
        cond: ${{inputs.Browser == 'chrome'}} && ${{inputs.Headed}}
        build: npm run test:chrome:headed
    - name: Run Cypress tests on ${{inputs.Browser}} Browser in ${{inputs.Headed}}
      uses: cypress-io/github-action@v6
      with: 
        cond: ${{inputs.Browser == 'chrome'}} && ${{!inputs.Headed}}
        build: npm run test:chrome
    - name: Run Cypress tests on ${{inputs.Browser}} Browser in ${{inputs.Headed}}
      uses: cypress-io/github-action@v6
      with: 
        cond: ${{inputs.Browser == 'firefox'}} && ${{!inputs.Headed}}
        build: npm run test:firefox
    - name: Run Cypress tests on ${{inputs.Browser}} Browser in ${{inputs.Headed}}
      uses: cypress-io/github-action@v6
      with: 
        cond: ${{inputs.Browser == 'firefox'}} && ${{inputs.Headed}}
        build: npm run test:firefox:headed
    - name: Run Cypress tests on ${{inputs.Browser}} Browser in ${{inputs.Headed}}
      uses: cypress-io/github-action@v6
      with: 
        cond: ${{inputs.Browser == 'electron'}} && ${{inputs.Headed}}
        build: npm run test:electron:headed
    - name: Run Cypress tests on ${{inputs.Browser}} Browser in ${{inputs.Headed}}
      uses: cypress-io/github-action@v6
      with: 
        cond: ${{inputs.Browser == 'electron'}} && ${{!inputs.Headed}}
        build: npm run test:electron