name: Trigger Test Manual with Configuration
on:
  workflow_dispatch:
    inputs:
      Browser:
        description: 'Select the Browser'
        options:
          - firefox
          - chrome
          - electron
        type: choice
        default: chrome
        required : true
      Headed:
        description: "Do you want to run tests in Headed mode??"
        type: boolean
        required: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm ci
    - name: Install Cypress
      run: npm install ypress
    - name: Run Cypress tests on ${{inputs.Browser}} Browser in Headed mode
      if: ${{inputs.Headed}}
      run: npm run test:${{inputs.Browser}}:headed
    - name: Run Cypress tests on ${{inputs.Browser}} Browser
      if: ${{!inputs.Headed}}
      run: npm run test:${{inputs.Browser}}

            
        